# Generated by Django 5.2.7 on 2026-04-14 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_society_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('committee', 'Committee'), ('resident', 'Resident')], default='resident', max_length=20),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='accounts.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'committee_members',
                'unique_together': {('society', 'role')},
            },
        ),
    ]
