# Generated by Django 5.2.7 on 2026-04-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_categories', to='accounts.society')),
            ],
            options={
                'db_table': 'maintenance_categories',
            },
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='accounts.society')),
            ],
            options={
                'db_table': 'dues',
                'unique_together': {('resident', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.maintenancecategory')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ledger', to='accounts.society')),
            ],
            options={
                'db_table': 'maintenance_ledger',
                'unique_together': {('society', 'category', 'month')},
            },
        ),
    ]
