# Generated by Django 5.2.7 on 2026-04-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bylaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(max_length=500)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bylaws', to='accounts.society')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_bylaws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bylaws',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
