# Generated by Django 5.2.7 on 2026-04-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useronlinestatus',
            name='online_status_online_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_rooms_residen_627328_idx',
            old_name='chat_rooms_res_comm_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_rooms_updated_dd240c_idx',
            old_name='chat_rooms_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_cc7f0e_idx',
            old_name='messages_room_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_fc300c_idx',
            old_name='messages_room_read_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_dele_e71162_idx',
            old_name='messages_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='messagevisibility',
            new_name='message_vis_user_id_1dd2d9_idx',
            old_name='visibility_user_hidden_idx',
        ),
    ]
