# Generated by Django 4.2 on 2026-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_useronlinestatus_online_status_online_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['is_online'], name='user_online_is_onli_1d7cc3_idx'),
        ),
    ]
